[pytest]
markers =
    valid: mark a test as valid scenario
    regression: mark a test as regression scenario
    parametrize: mark a test as parametrize scenario
    invalid: mark a test as invalid scenario
