[pytest]
markers =
    positive: mark a test as positive scenario
    negative: mark a test as negative scenario
    mixed: mark a test as mixed scenario
    edge: mark a test as edge scenario
    valid: mark a test as valid scenario
    performance: mark a test as performance scenario
    precision: mark a test as precision scenario
