# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonunittesting using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonunittesting using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=addition_9ccff787e3
ROOST_METHOD_SIG_HASH=addition_77ffd3333b


Scenario 1: Test for Positive Numbers
Details:
  TestName: test_addition_of_positive_numbers
  Description: This test is to verify that the addition function correctly adds two given positive numbers.
Execution:
  Arrange: No initialization of objects is required as the function doesn't rely on any.
  Act: Invoke the addition function with two positive integer numbers as parameters.
  Assert: The expected outcome is the correct sum of the two input numbers. Validate this by comparing to a pre-calculated sum.
Validation:
  Rationalize: This test validates the basic functionality of the addition function, ensuring the result is correct when working with positive numbers.

Scenario 2: Negative Numbers Test
Details:
  TestName: test_addition_of_negative_numbers
  Description: This test will check if the function correctly handles the addition of two negative numbers.
Execution:
  Arrange: No initialization of objects or environment is needed.
  Act: Invoke the addition function with two negative numbers.
  Assert: The expected outcome is the sum of the two negative numbers which will be a negative number. Compare it with the pre-calculated sum.
Validation:
  Rationalize: This test is important to confirm that the addition function handles negative numbers correctly.

Scenario 3: Positive and Negative Numbers Test
Details:
  TestName: test_addition_of_positive_and_negative_numbers
  Description: This test will validate the correct addition of a positive number and a negative number.
Execution:
  Arrange: No initialization or environment setup required.
  Act: Call the addition function with a positive number and negative number as parameters.
  Assert: The expected outcome is the correct sum of the these values. The result will be positive if the positive number is greater than the negative number and vice versa. Compare the actual sum with the pre-calculated sum.
Validation:
  Rationalize: This test ensures that the function handles scenarios where inputs comprise both positive and negative numbers.

Scenario 4: Test for Floating Point Numbers
Details:
  TestName: test_addition_of_float_numbers
  Description: This test will check whether the function can handle and correctly add two floating point numbers.
Execution:
  Arrange: No setup required.
  Act: Invoke the addition function with two floating point numbers as parameters.
  Assert: The expected result is a correct sum of these two floating point numbers. Compare this with a pre-calculated sum.
Validation:
  Rationalize: This test is necessary to confirm that the addition function handles decimal numbers correctly.
"""

# ********RoostGPT********
import pytest
from calc import SimpleCalculator

class Test_SimpleCalculatorAddition():
    
    # Test Scenario 1 : Test for Positive Numbers
    def test_addition_of_positive_numbers(self):
        # Arrange
        num1, num2 = 4, 5
        expected_sum = 9
        
        # Act
        actual_sum = SimpleCalculator.addition(num1, num2)
        
        # Assert
        assert actual_sum == expected_sum, "Addition of two positives numbers is not correct"
        
        
    # Test Scenario 2 : Test for Negative Numbers
    def test_addition_of_negative_numbers(self):
        # Arrange
        num1, num2 = -4, -5
        expected_sum = -9
        
        # Act
        actual_sum = SimpleCalculator.addition(num1, num2)
        
        # Assert
        assert actual_sum == expected_sum, "Addition of two negative numbers is not correct"
        
 
    # Test Scenario 3 : Test for Positive and Negative Numbers
    def test_addition_of_positive_and_negative_numbers(self):
        # Arrange
        num1, num2 = -4, 5
        expected_sum = 1

        # Act
        actual_sum = SimpleCalculator.addition(num1, num2)

        # Assert
        assert actual_sum == expected_sum, "Addition of positive and negative numbers is not correct"
        
    
    # Test Scenario 4 : Test for Floating Point Numbers
    def test_addition_of_float_numbers(self):
        # Arrange
        num1, num2 = 4.2, 5.3
        expected_sum = 9.5

        # Act
        actual_sum = SimpleCalculator.addition(num1, num2)

        # Assert
        assert actual_sum == expected_sum, "Addition of two floating point numbers is not correct"
