# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonunittesting using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonunittesting using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=division_d77e58cf69
ROOST_METHOD_SIG_HASH=division_eae366bb2d


Scenario 1: Validate regular division function
Details:
  TestName: test_regular_division
  Description: This test will validate the function if it is correctly dividing two numbers. We will take two randomly selected numbers.
Execution:
  Arrange: Pick two random numbers, num1 and num2, where num2!=0
  Act: Call the division(num1, num2)
  Assert: The expected outcome will be the float value of num1 divided by num2. This will be verified against the result from the function.
Validation:
  Rationalize: This test is essential as it checks the primary functionality of the division operation. It ensures num1 is divided by num2 correctly.

Scenario 2: Validate division by Zero
Details:
  TestName: test_division_by_zero
  Description: This test will validate the function against a division by zero scenario.
Execution:
  Arrange: Pick any random number as num1 and set num2 as zero.
  Act: Call the division(num1, num2)
  Assert: The expected outcome will be the message "Cannot divide by zero". This will be verified against the error message from the function.
Validation:
  Rationalize: This is an essential test scenario as division by zero should always be handled in any division operation. It checks if the code correctly handles this exception scenario.

Scenario 3: Validate negative division
Details:
  TestName: test_negative_division
  Description: This test will validate if the function can handle negative numbers.
Execution:
  Arrange: Select two negative numbers num1 and num2 where num2!=0.
  Act: Call the division function with num1 and num2.
  Assert: The expected outcome will be the float result of num1 divided by num2. This will be verified against the expected outcome.
Validation:
  Rationalize: This scenario ensures that division is also possible for negative numbers. It checks if the function is versatile enough to handle negative integers.

Scenario 4: Validate division of fractions
Details:
  TestName: test_fractional_division
  Description: This test will validate if the function can handle fractional numbers.
Execution:
  Arrange: Select two fractional numbers num1 and num2 where num2!=0.
  Act: Call the division function with num1 and num2.
  Assert: The expected outcome will be the float result of num1 divided by num2. This will be verified against the expected outcome.
Validation:
  Rationalize: This scenario checks the function's flexibility to handle fractional numbers. It ensures accurate results even when non-integer numbers are used.
"""

# ********RoostGPT********
import pytest
import random
from calc import division

class Test_CalcDivision:

    @pytest.mark.regression
    @pytest.mark.positive
    def test_regular_division(self):
        num1, num2 = random.randint(1, 100), random.randint(1, 100)
        result = division(num1, num2)
        assert result == num1 / num2, f"Expected {num1/num2} but got {result}"

    @pytest.mark.regression
    @pytest.mark.negative
    def test_division_by_zero(self):
        num1, num2 = random.randint(1, 100), 0
        result = division(num1, num2)
        assert result == "Cannot divide by zero", f"Expected 'Cannot divide by zero' but got {result}"

    @pytest.mark.regression
    @pytest.mark.negative
    def test_negative_division(self):
        num1, num2 = random.randint(-100, -1), random.randint(-100, -1)
        result = division(num1, num2)
        assert result == num1 / num2, f"Expected {num1/num2} but got {result}"

    @pytest.mark.regression
    @pytest.mark.positive
    def test_fractional_division(self):
        num1, num2 = random.uniform(0.1, 10.0), random.uniform(0.1, 10.0)
        result = division(num1, num2)
        assert pytest.approx(result) == num1 / num2, f"Expected {num1/num2} but got {result}"
