# ROOST_METHOD_HASH=SimpleCalculator.subtraction_68d9a9a59f
# ROOST_METHOD_SIG_HASH=SimpleCalculator.subtraction_c085e74db2

"""Tests for `calc.SimpleCalculator.subtraction`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:13-15
# Scenarios:
#   - [happy_path] positive_integers_positive_result: Verify subtraction of two positive integers where the first is larger than the second.
#   - [happy_path] positive_integers_negative_result: Verify subtraction where the second number is larger than the first, resulting in a negative integer.
#   - [happy_path] negative_integers: Verify subtraction of two negative integers.
#   - [edge_case] floating_point_numbers: Verify subtraction with floating point numbers.
#   - [edge_case] zero_result: Verify that subtracting a number from itself results in zero.
#   - [error_path] invalid_type_string: Verify that passing a string instead of a number raises a TypeError.

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers_positive_result():
    """Verify subtraction of two positive integers where the first is larger than the second."""
    result = SimpleCalculator.subtraction(10, 7)
    assert result == 3

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers_negative_result():
    """Verify subtraction where the second number is larger than the first, resulting in a negative integer."""
    result = SimpleCalculator.subtraction(5, 12)
    assert result == -7

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_integers():
    """Verify subtraction of two negative integers."""
    result = SimpleCalculator.subtraction(-10, -3)
    assert result == -7

@pytest.mark.generated
@pytest.mark.edge_case
def test_floating_point_numbers():
    """Verify subtraction with floating point numbers."""
    result = SimpleCalculator.subtraction(10.5, 2.5)
    assert result == 8.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_zero_result():
    """Verify that subtracting a number from itself results in zero."""
    result = SimpleCalculator.subtraction(100, 100)
    assert result == 0

@pytest.mark.generated
@pytest.mark.error_path
def test_invalid_type_string():
    """Verify that passing a string instead of a number raises a TypeError."""
    with pytest.raises(TypeError):
        SimpleCalculator.subtraction("10", 5)
