# ROOST_METHOD_HASH=SimpleCalculator.subtraction_68d9a9a59f
# ROOST_METHOD_SIG_HASH=SimpleCalculator.subtraction_c085e74db2

"""Tests for `calc.SimpleCalculator.subtraction`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:13-15
# Scenarios:
#   - [happy_path] positive_integers: Verify subtraction with two positive integers.
#   - [happy_path] negative_integers: Verify subtraction with two negative integers.
#   - [happy_path] floating_point_numbers: Verify subtraction with floating point numbers.
#   - [edge_case] zero_operands: Verify subtraction when both operands are zero.
#   - [happy_path] mixed_signs: Verify subtraction of a negative number from a positive number.
#   - [error_path] invalid_types: Verify that passing a string and an integer raises a TypeError.

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers():
    """Verify subtraction with two positive integers."""
    result = SimpleCalculator.subtraction(10, 5)
    assert result == 5

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_integers():
    """Verify subtraction with two negative integers."""
    result = SimpleCalculator.subtraction(-5, -10)
    assert result == 5

@pytest.mark.generated
@pytest.mark.happy_path
def test_floating_point_numbers():
    """Verify subtraction with floating point numbers."""
    result = SimpleCalculator.subtraction(10.5, 2.5)
    assert result == 8.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_zero_operands():
    """Verify subtraction when both operands are zero."""
    result = SimpleCalculator.subtraction(0, 0)
    assert result == 0

@pytest.mark.generated
@pytest.mark.happy_path
def test_mixed_signs():
    """Verify subtraction of a negative number from a positive number."""
    result = SimpleCalculator.subtraction(10, -5)
    assert result == 15

@pytest.mark.generated
@pytest.mark.error_path
def test_invalid_types():
    """Verify that passing a string and an integer raises a TypeError."""
    with pytest.raises(TypeError):
        SimpleCalculator.subtraction("10", 5)
