# ROOST_METHOD_HASH=SimpleCalculator.multiplication_b85031f6ad
# ROOST_METHOD_SIG_HASH=SimpleCalculator.multiplication_c14ad406cb

"""Tests for `calc.SimpleCalculator.multiplication`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:18-20
# Scenarios:
#   - [happy_path] happy_path_positive: Verify that multiplying two positive integers returns the correct product.
#   - [happy_path] negative_numbers: Verify that multiplying a negative integer by a positive integer returns a negative product.
#   - [edge_case] multiply_by_zero: Verify that multiplying any number by zero returns zero.
#   - [happy_path] floating_point: Verify that multiplying floating point numbers returns the correct product.
#   - [edge_case] identity_multiplication: Verify that multiplying a number by one returns the number itself.
#   - [happy_path] two_negatives: Verify that multiplying two negative integers returns a positive product.

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_positive():
    """Verify that multiplying two positive integers returns the correct product."""
    result = SimpleCalculator.multiplication(3, 5)
    assert result == 15

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_numbers():
    """Verify that multiplying a negative integer by a positive integer returns a negative product."""
    result = SimpleCalculator.multiplication(-4, 7)
    assert result == -28

@pytest.mark.generated
@pytest.mark.edge_case
def test_multiply_by_zero():
    """Verify that multiplying any number by zero returns zero."""
    result = SimpleCalculator.multiplication(10, 0)
    assert result == 0

@pytest.mark.generated
@pytest.mark.happy_path
def test_floating_point():
    """Verify that multiplying floating point numbers returns the correct product."""
    result = SimpleCalculator.multiplication(2.5, 4.0)
    assert result == 10.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_identity_multiplication():
    """Verify that multiplying a number by one returns the number itself."""
    result = SimpleCalculator.multiplication(123, 1)
    assert result == 123

@pytest.mark.generated
@pytest.mark.happy_path
def test_two_negatives():
    """Verify that multiplying two negative integers returns a positive product."""
    result = SimpleCalculator.multiplication(-2, -6)
    assert result == 12
