# ROOST_METHOD_HASH=SimpleCalculator.multiplication_b85031f6ad
# ROOST_METHOD_SIG_HASH=SimpleCalculator.multiplication_c14ad406cb

"""Tests for `calc.SimpleCalculator.multiplication`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:18-20
# Scenarios:
#   - [happy_path] positive_integers: Verify multiplication of two positive integers.
#   - [happy_path] positive_floats: Verify multiplication of two positive floating-point numbers.
#   - [edge_case] multiply_by_zero: Verify that multiplying any number by zero results in zero.
#   - [happy_path] negative_and_positive: Verify multiplication of a negative number and a positive number.
#   - [happy_path] two_negatives_result_in_positive: Verify that multiplying two negative numbers results in a positive number.
#   - [edge_case] multiplication_by_one_identity: Verify that multiplying a number by one returns the number itself (identity property).

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers():
    """Verify multiplication of two positive integers."""
    result = SimpleCalculator.multiplication(5, 10)
    assert result == 50

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_floats():
    """Verify multiplication of two positive floating-point numbers."""
    result = SimpleCalculator.multiplication(2.5, 4.0)
    assert result == 10.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_multiply_by_zero():
    """Verify that multiplying any number by zero results in zero."""
    result = SimpleCalculator.multiplication(100, 0)
    assert result == 0

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_and_positive():
    """Verify multiplication of a negative number and a positive number."""
    result = SimpleCalculator.multiplication(-5, 6)
    assert result == -30

@pytest.mark.generated
@pytest.mark.happy_path
def test_two_negatives_result_in_positive():
    """Verify that multiplying two negative numbers results in a positive number."""
    result = SimpleCalculator.multiplication(-4, -3)
    assert result == 12

@pytest.mark.generated
@pytest.mark.edge_case
def test_multiplication_by_one_identity():
    """Verify that multiplying a number by one returns the number itself (identity property)."""
    result = SimpleCalculator.multiplication(42, 1)
    assert result == 42
