# ROOST_METHOD_HASH=division_d77e58cf69
# ROOST_METHOD_SIG_HASH=division_eae366bb2d

"""Tests for `calc.division`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:22-27
# Scenarios:
#   - [happy_path] positive_integers_exact: Test division with two positive integers that result in a whole number.
#   - [happy_path] positive_integers_float: Test division with two positive integers that result in a float.
#   - [edge_case] divide_by_int_zero: Test division by integer zero, which should return the specific error string.
#   - [edge_case] divide_by_float_zero: Test division by float zero, which should also return the error string.
#   - [happy_path] negative_numerator: Test division with a negative numerator.
#   - [edge_case] zero_numerator_dividend: Test division where the numerator is zero.

import pytest
from calc import division

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers_exact():
    """Test division with two positive integers that result in a whole number."""
    result = division(10, 2)
    assert result == 5.0

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers_float():
    """Test division with two positive integers that result in a float."""
    result = division(5, 2)
    assert result == 2.5

@pytest.mark.generated
@pytest.mark.edge_case
def test_divide_by_int_zero():
    """Test division by integer zero, which should return the specific error string."""
    result = division(10, 0)
    assert result == "Cannot divide by zero"

@pytest.mark.generated
@pytest.mark.edge_case
def test_divide_by_float_zero():
    """Test division by float zero, which should also return the error string."""
    result = division(10, 0.0)
    assert result == "Cannot divide by zero"

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_numerator():
    """Test division with a negative numerator."""
    result = division(-10, 2)
    assert result == -5.0

@pytest.mark.generated
@pytest.mark.happy_path
def test_zero_numerator_dividend():
    """Test division where the numerator is zero."""
    result = division(0, 5)
    assert result == 0.0
