# ROOST_METHOD_HASH=division_d77e58cf69
# ROOST_METHOD_SIG_HASH=division_eae366bb2d

"""Tests for `calc.division`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:22-27
# Scenarios:
#   - [happy_path] positive_integers: Test division with two positive integers.
#   - [happy_path] negative_dividend: Test division with a negative dividend.
#   - [happy_path] floating_point_numbers: Test division with floating point numbers.
#   - [edge_case] division_by_zero_int: Test division by zero returns the expected error string.
#   - [edge_case] division_by_zero_float: Test division by zero with a float zero.
#   - [edge_case] zero_dividend: Test division where the dividend is zero.

import pytest
from calc import division

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers():
    """Test division with two positive integers."""
    assert division(10, 2) == 5.0

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_dividend():
    """Test division with a negative dividend."""
    assert division(-10, 2) == -5.0

@pytest.mark.generated
@pytest.mark.happy_path
def test_floating_point_numbers():
    """Test division with floating point numbers."""
    assert division(7.5, 2.5) == 3.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_division_by_zero_int():
    """Test division by zero returns the expected error string."""
    assert division(10, 0) == "Cannot divide by zero"

@pytest.mark.generated
@pytest.mark.edge_case
def test_division_by_zero_float():
    """Test division by zero with a float zero."""
    assert division(10, 0.0) == "Cannot divide by zero"

@pytest.mark.generated
@pytest.mark.edge_case
def test_zero_dividend():
    """Test division where the dividend is zero."""
    assert division(0, 5) == 0.0
