# ROOST_METHOD_HASH=SimpleCalculator.addition_9ccff787e3
# ROOST_METHOD_SIG_HASH=SimpleCalculator.addition_77ffd3333b

"""Tests for `calc.SimpleCalculator.addition`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:8-10
# Scenarios:
#   - [happy_path] add_positive_integers: Verify that adding two positive integers returns their correct sum.
#   - [happy_path] add_negative_integers: Verify that adding two negative integers returns their correct sum.
#   - [happy_path] add_floats: Verify that adding two floating point numbers returns their correct sum.
#   - [edge_case] add_zero: Verify that adding zero to a number returns the number itself (additive identity).
#   - [happy_path] add_mixed_types: Verify that adding an integer and a float returns the correct float sum.
#   - [error_path] type_error_on_mixed_string: Verify that attempting to add an integer and a string raises a TypeError.

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_positive_integers():
    """Verify that adding two positive integers returns their correct sum."""
    result = SimpleCalculator.addition(10, 20)
    assert result == 30

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_negative_integers():
    """Verify that adding two negative integers returns their correct sum."""
    result = SimpleCalculator.addition(-10, -20)
    assert result == -30

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_floats():
    """Verify that adding two floating point numbers returns their correct sum."""
    result = SimpleCalculator.addition(1.5, 2.5)
    assert result == 4.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_add_zero():
    """Verify that adding zero to a number returns the number itself (additive identity)."""
    result = SimpleCalculator.addition(100, 0)
    assert result == 100

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_mixed_types():
    """Verify that adding an integer and a float returns the correct float sum."""
    result = SimpleCalculator.addition(10, 5.5)
    assert result == 15.5

@pytest.mark.generated
@pytest.mark.error_path
def test_type_error_on_mixed_string():
    """Verify that attempting to add an integer and a string raises a TypeError."""
    with pytest.raises(TypeError):
        SimpleCalculator.addition(10, '5')
