# ROOST_METHOD_HASH=SimpleCalculator.addition_9ccff787e3
# ROOST_METHOD_SIG_HASH=SimpleCalculator.addition_77ffd3333b

"""Tests for `calc.SimpleCalculator.addition`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:8-10
# Scenarios:
#   - [happy_path] add_positive_integers: Verify that adding two positive integers returns the correct sum.
#   - [happy_path] add_negative_integers: Verify that adding two negative integers returns the correct sum.
#   - [happy_path] add_floats: Verify that adding two floating point numbers returns the correct sum.
#   - [edge_case] add_zero: Verify that adding zero to a number returns the number itself.
#   - [edge_case] add_large_integers: Verify that adding very large integers works correctly.
#   - [error_path] add_invalid_types: Verify that passing incompatible types (string and integer) raises a TypeError.

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_positive_integers():
    """Verify that adding two positive integers returns the correct sum."""
    result = SimpleCalculator.addition(10, 20)
    assert result == 30

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_negative_integers():
    """Verify that adding two negative integers returns the correct sum."""
    result = SimpleCalculator.addition(-10, -20)
    assert result == -30

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_floats():
    """Verify that adding two floating point numbers returns the correct sum."""
    result = SimpleCalculator.addition(1.5, 2.5)
    assert result == 4.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_add_zero():
    """Verify that adding zero to a number returns the number itself."""
    result = SimpleCalculator.addition(5, 0)
    assert result == 5

@pytest.mark.generated
@pytest.mark.edge_case
def test_add_large_integers():
    """Verify that adding very large integers works correctly."""
    result = SimpleCalculator.addition(10**15, 10**15)
    assert result == 2 * 10**15

@pytest.mark.generated
@pytest.mark.error_path
def test_add_invalid_types():
    """Verify that passing incompatible types (string and integer) raises a TypeError."""
    with pytest.raises(TypeError):
        SimpleCalculator.addition("1", 2)
