# ROOST_METHOD_HASH=SimpleCalculator.addition_9ccff787e3
# ROOST_METHOD_SIG_HASH=SimpleCalculator.addition_77ffd3333b

"""Tests for `calc.SimpleCalculator.addition`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:8-10
# Scenarios:
#   - [happy_path] add_positive_integers: Verify that adding two positive integers returns their correct sum.
#   - [happy_path] add_negative_integers: Verify that adding two negative integers returns their correct sum.
#   - [happy_path] add_floats: Verify that adding two floating-point numbers returns their correct sum.
#   - [edge_case] add_zero_identity: Verify that adding zero to a number returns the original number (additive identity).
#   - [edge_case] add_large_integers: Verify that adding very large integers works correctly in Python.
#   - [error_path] add_invalid_types_raises_error: Verify that passing a non-numeric type (string) results in a TypeError when attempting addition with an integer.

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_positive_integers():
    """Verify that adding two positive integers returns their correct sum."""
    result = SimpleCalculator.addition(10, 20)
    assert result == 30

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_negative_integers():
    """Verify that adding two negative integers returns their correct sum."""
    result = SimpleCalculator.addition(-10, -20)
    assert result == -30

@pytest.mark.generated
@pytest.mark.happy_path
def test_add_floats():
    """Verify that adding two floating-point numbers returns their correct sum."""
    result = SimpleCalculator.addition(1.5, 2.5)
    assert result == 4.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_add_zero_identity():
    """Verify that adding zero to a number returns the original number (additive identity)."""
    result = SimpleCalculator.addition(5, 0)
    assert result == 5

@pytest.mark.generated
@pytest.mark.edge_case
def test_add_large_integers():
    """Verify that adding very large integers works correctly in Python."""
    result = SimpleCalculator.addition(10**18, 10**18)
    assert result == 2 * 10**18

@pytest.mark.generated
@pytest.mark.error_path
def test_add_invalid_types_raises_error():
    """Verify that passing a non-numeric type (string) results in a TypeError when attempting addition with an integer."""
    with pytest.raises(TypeError):
        SimpleCalculator.addition("5", 3)
