# ROOST_METHOD_HASH=division_d77e58cf69
# ROOST_METHOD_SIG_HASH=division_eae366bb2d

"""Tests for `calc.division`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:22-27
# Scenarios:
#   - [happy_path] test_division_positive_integers: Verify that dividing two positive integers returns the correct float quotient.
#   - [happy_path] test_division_negative_numbers: Verify that division works correctly with negative numbers.
#   - [happy_path] test_division_float_result: Verify that division resulting in a non-integer float is handled correctly.
#   - [edge_case] test_division_by_zero_int: Verify that dividing by integer zero returns the expected error message string.
#   - [edge_case] test_division_by_zero_float: Verify that dividing by float zero (0.0) also returns the error message string.
#   - [edge_case] test_division_zero_dividend: Verify that zero divided by a non-zero number returns 0.0.

import pytest
from calc import division

@pytest.mark.generated
@pytest.mark.happy_path
def test_division_positive_integers():
    """Verify that dividing two positive integers returns the correct float quotient."""
    result = division(10, 2)
    assert result == 5.0

@pytest.mark.generated
@pytest.mark.happy_path
def test_division_negative_numbers():
    """Verify that division works correctly with negative numbers."""
    result = division(-10, 2)
    assert result == -5.0

@pytest.mark.generated
@pytest.mark.happy_path
def test_division_float_result():
    """Verify that division resulting in a non-integer float is handled correctly."""
    result = division(5, 2)
    assert result == 2.5

@pytest.mark.generated
@pytest.mark.edge_case
def test_division_by_zero_int():
    """Verify that dividing by integer zero returns the expected error message string."""
    result = division(10, 0)
    assert result == "Cannot divide by zero"

@pytest.mark.generated
@pytest.mark.edge_case
def test_division_by_zero_float():
    """Verify that dividing by float zero (0.0) also returns the error message string."""
    result = division(10.0, 0.0)
    assert result == "Cannot divide by zero"

@pytest.mark.generated
@pytest.mark.edge_case
def test_division_zero_dividend():
    """Verify that zero divided by a non-zero number returns 0.0."""
    result = division(0, 10)
    assert result == 0.0
