# ROOST_METHOD_HASH=SimpleCalculator.multiplication_b85031f6ad
# ROOST_METHOD_SIG_HASH=SimpleCalculator.multiplication_c14ad406cb

"""Tests for `calc.SimpleCalculator.multiplication`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:18-20
# Scenarios:
#   - [happy_path] positive_integers: Verify that multiplying two positive integers returns the correct product.
#   - [happy_path] negative_numbers: Verify that multiplying a positive and a negative integer returns a negative product.
#   - [edge_case] zero_multiplication: Verify that multiplying any number by zero returns zero.
#   - [happy_path] float_multiplication: Verify that multiplying floating point numbers returns the correct product.
#   - [happy_path] two_negatives: Verify that multiplying two negative numbers returns a positive product.
#   - [error_path] incompatible_types: Verify that attempting to multiply two strings raises a TypeError.

# NB: roost-pytest could not get this test green.
#     target: calc.SimpleCalculator.multiplication
#     cause:  unknown__see_diagnostic_message
#     note:   The test file is correctly implemented and covers all scenarios. However, both `pytest_run` and `pytest_collect` fail with an environment-level error: `unrecognized arguments: --report-log`. This sugg
# This file is committed as a SKIPPED stub so the agent's draft
# is preserved for review. Either fix the failing scenarios and
# remove the pytestmark below, or delete the file outright. See
# the runreport.json for full diagnostics.

pytestmark = pytest.mark.skip(reason='agent could not produce a green test (unknown__see_diagnostic_message)')

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers():
    """Verify that multiplying two positive integers returns the correct product."""
    result = SimpleCalculator.multiplication(10, 5)
    assert result == 50

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_numbers():
    """Verify that multiplying a positive and a negative integer returns a negative product."""
    result = SimpleCalculator.multiplication(-6, 7)
    assert result == -42

@pytest.mark.generated
@pytest.mark.edge_case
def test_zero_multiplication():
    """Verify that multiplying any number by zero returns zero."""
    result = SimpleCalculator.multiplication(0, 99)
    assert result == 0

@pytest.mark.generated
@pytest.mark.happy_path
def test_float_multiplication():
    """Verify that multiplying floating point numbers returns the correct product."""
    result = SimpleCalculator.multiplication(2.5, 4.0)
    assert result == 10.0

@pytest.mark.generated
@pytest.mark.happy_path
def test_two_negatives():
    """Verify that multiplying two negative numbers returns a positive product."""
    result = SimpleCalculator.multiplication(-5, -5)
    assert result == 25

@pytest.mark.generated
@pytest.mark.error_path
def test_incompatible_types():
    """Verify that attempting to multiply two strings raises a TypeError."""
    with pytest.raises(TypeError):
        SimpleCalculator.multiplication("a", "b")
