# ROOST_METHOD_HASH=SimpleCalculator.subtraction_68d9a9a59f
# ROOST_METHOD_SIG_HASH=SimpleCalculator.subtraction_c085e74db2

"""Tests for `calc.SimpleCalculator.subtraction`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:13-15
# Scenarios:
#   - [happy_path] positive_integers: Verify subtraction of two positive integers.
#   - [happy_path] negative_integers: Verify subtraction of two negative integers.
#   - [happy_path] floating_point: Verify subtraction of floating point numbers.
#   - [edge_case] subtract_zero: Verify that subtracting zero returns the original number.
#   - [edge_case] result_zero: Verify that subtracting a number from itself returns zero.
#   - [error_path] type_error_string: Verify that passing a string as an argument raises a TypeError.

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers():
    """Verify subtraction of two positive integers."""
    result = SimpleCalculator.subtraction(10, 5)
    assert result == 5

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_integers():
    """Verify subtraction of two negative integers."""
    result = SimpleCalculator.subtraction(-1, -5)
    assert result == 4

@pytest.mark.generated
@pytest.mark.happy_path
def test_floating_point():
    """Verify subtraction of floating point numbers."""
    result = SimpleCalculator.subtraction(10.5, 0.5)
    assert result == 10.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_subtract_zero():
    """Verify that subtracting zero returns the original number."""
    result = SimpleCalculator.subtraction(5, 0)
    assert result == 5

@pytest.mark.generated
@pytest.mark.edge_case
def test_result_zero():
    """Verify that subtracting a number from itself returns zero."""
    result = SimpleCalculator.subtraction(5, 5)
    assert result == 0

@pytest.mark.generated
@pytest.mark.error_path
def test_type_error_string():
    """Verify that passing a string as an argument raises a TypeError."""
    with pytest.raises(TypeError):
        SimpleCalculator.subtraction("10", 5)
